### ISSUE TITLE
Rebase broke Build Github Action

### ISSUE THREAD

**Issue by sobolevn** [cirrus-actions/rebase#16]
Hi, thanks for building this tool!

I am trying to integrate in to my workflow, but something is not working well: https://github.com/sobolevn/itmo-2019/pull/11

After a rebase I am left with this:
<img width="679" alt="Снимок экрана 2019-09-14 в 13 41 01" src="https://user-images.githubusercontent.com/4660275/64906957-4eddc880-d6f5-11e9-9b79-81a73ee3dd71.png">

That's how my `build` workflow looks like: https://github.com/sobolevn/itmo-2019/blob/master/.github/workflows/build.yml

What's wrong?

**Comment by sobolevn** [comment]
I can reproduce it: https://github.com/sobolevn/itmo-2019/pull/12

**Comment by fkorotkov** [comment]
@sobolevn I don't see that you use rebase action either in the latest version of your workflow or in the [one when you created the issue](https://github.com/sobolevn/itmo-2019/commit/dfed4d2f5d237c3fe85700eac4c987d3a8437504#diff-898e737ee4e56ba042bda31764bed49e).

Anyways, based on the screenshot it seems that you've configured a required status check named `Build` but you don't  have anything that produces such check yet.

**Comment by sobolevn** [comment]
Well, let's dig into it.

That's what my merge requires:
<img width="682" alt="Снимок экрана 2019-09-14 в 21 41 31" src="https://user-images.githubusercontent.com/4660275/64912458-7013d880-d738-11e9-8f0d-482cdf326b53.png">

And it works perfectly fine for my regular setup: 
<img width="761" alt="Снимок экрана 2019-09-14 в 21 43 31" src="https://user-images.githubusercontent.com/4660275/64912481-c254f980-d738-11e9-9392-271c5c4449a8.png">

Link to the correct PR: https://github.com/sobolevn/itmo-2019/pull/17

That's the exact configuration I had when I added your action: https://github.com/sobolevn/itmo-2019/blob/4ab336d1d18f821d3fa5bf8d6125a34cc401a3ea/.github/workflows/comments.yml You can see the result of the rebase on the screenshots and inside the linked PRs.

After finding this issue I decided to remove this action, because it is obviously not working as intended. Any ideas where to look? 

P.S. You can consider it as closed / won't fix or reopen in case you want to debug this error.

**Comment by fkorotkov** [comment]
Unfortunately it's hard to troubleshoot the issue since you've deleted branches and the action from master. GitHub Actions apply workflows only from master so any runs of `rebase` actions are no longer visible: https://github.com/sobolevn/itmo-2019/actions. 

From the screenshots it seems `rebase` action worked as expected: rebased and force pushed your branch. Not clear why other actions were not triggered after the force push 🤷‍♂

**Comment by gsuess** [comment]
My guess is that this is by design.

When the `rebase` triggers a force-push, a workflow which is supposed to be triggered by that push is not triggered when this push executed by the `rebase` action.

I managed to work around this by changing the trigger from this:

```yaml
on: push
```
to this:

```yaml
on:
  push:
  workflow_run:
    workflows: ["Automatic Rebase"]
    types:
      - completed
```

**Comment by gsuess** [comment]
Related thread https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854
