### ISSUE TITLE
parallel execution

### ISSUE THREAD

**Issue by stefan-enway** [cirrus-actions/rebase#18]
our developers are quite happily using this feature (and are loving it!) but i noticed that this action is never executed in parallel. is there a way in the action api to enable that?

**Comment by fkorotkov** [comment]
I don't think that we do any limitation regarding it. And I think GitHub actions don't enforce single action execution. 🤔 On which repository you  saw this behaviour?

**Comment by stefan-enway** [comment]
Our main private one. i was going to post a screenshot but now it only shows "17 hours ago" and i cant see an exact time when the action started (besides going to the logs/when the comment is posted). It seems there is in invisible queue because if colleagues started an action mine is not visible, later i see that it was executed though.

**Comment by stefan-enway** [comment]
i found the limit via [Action Limits](https://scotch.io/bar-talk/introducing-github-actions) : 
- Each workflow can run for a maximum of 58 minutes including queuing and execution.
- Each workflow can run a maximum of 100 actions
- A repository can run a maximum of 2 workflows concurrently
- A task performed within an action cannot trigger other actions.

We are hitting the 2 workflow limit as it looks like. i am not sure if even two are executed concurrently. We have lots of PRs and sometimes (like after a meeting) a couple of dev one to merge an previously approved PR. We require them to rebase (opposed to pressing the merge button) so we have sometimes a little race to rebase, as after each PR merge to master everybody hast to rebase again ;)
