### ISSUE TITLE
Debug help

### ISSUE THREAD

**Issue by robertpro** [cirrus-actions/rebase#21]
How can I debug `rebase` action? is not working for me, and I don't see any error anywhere.

I created a test branch, which has the `.github/workflows/rebase.yml` file, then I created a PR from the `test-rebase` branch to develop (we don't merge to master directly). After that I write the `/rebase` command that is not working for me.

I don't really see how to debug it or how can I make it work.

**Comment by fkorotkov** [comment]
I don't think GotHub actions yet support reading config from a target branch. AFAIK they read configs from the default branch so you'll need to merge first.

**Comment by robertpro** [comment]
In my case this is not working yet, I merged the code into `develop` and `master`, then I tried a `/rebase` and it does nothing...

![image](https://user-images.githubusercontent.com/8595170/65802653-f02b3c80-e141-11e9-9ed0-23795fefdd75.png)

**Comment by robertpro** [comment]
@fkorotkov I think this is not your action problem, going to learn about GH actions and if I think this is wrong, I will open this issue again, thanks!

**Comment by ycjcl868** [comment]
+ 1
