### ISSUE TITLE
Fails to rebase

### ISSUE THREAD

**Issue by dogmatic69** [cirrus-actions/rebase#32]
Process:

1. Have repo
1. Create branch
1. Make edit to a file, commit and push branch (single white space in file a)
1. create PR
1. make commit on master and push. (single white space in file b)
1. Confirm message that branch is behind in PR
1. comment `/rebase`

Output:
```
+ git rebase origin/master
First, rewinding head to replay your work on top of it...
Applying: init
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
CONFLICT (add/add): Merge conflict in terraform/services/main.tf
Auto-merging terraform/services/main.tf
CONFLICT (add/add): Merge conflict in terraform/permissions/main.tf
Auto-merging terraform/permissions/main.tf
CONFLICT (add/add): Merge conflict in terraform/infrastructure/main.tf
Auto-merging terraform/infrastructure/main.tf
CONFLICT (add/add): Merge conflict in docker-compose.yml
Auto-merging docker-compose.yml
CONFLICT (add/add): Merge conflict in README.md
Auto-merging README.md
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging .gitignore
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 init
Resolve all conflicts manually, mark them as resolved with
```
None of the files listed were part of the test. `Applying: init` indicates it is rebasing from the begining of time?

Running the rebase locally for the PR branch gives the following:
```
$ git rebase origin/master 
First, rewinding head to replay your work on top of it...
Fast-forwarded tt to origin/master.
```

**Comment by dogmatic69** [comment]
I've tested so more, if I use the `/rebase` command when there is no changes in master it will run successfully. If i then add any change to master `/rebase` fails with the same error as above.

**Comment by ErikSchierboom** [comment]
@fkorotkov I've experienced the same issue. To see what is happening, you can go to https://github.com/exercism/v3/pull/147. This is a minor PR and I've asked it to be rebased in a comment. The comment is recognized and the rebase is started. However, the rebase fails due to apparent merge conflicts: https://github.com/exercism/v3/runs/395042326

This is weird though, because doing `git fetch` and then `git rebase origin/master` works. I've also tried following the steps at https://github.com/cirrus-actions/rebase/blob/master/entrypoint.sh#L68, but they also work locally.

Any ideas what could be wrong?

If you'd like to do some digging together, let me know.

**Comment by dogmatic69** [comment]
@fkorotkov I've posted my results of running the command `git rebase origin/master` locally already. It works perfectly fine. :(

My repo is private, but @ErikSchierboom has the exact same issue and its public so it is at least reproducible.

**Comment by dogmatic69** [comment]
I keep trying various PRs but I can not get it to rebase. Here are the logs from the action vs me manually running the commands on a fresh clone (on the same branch as the PR)

# Broken Action

```
Branch 'rfc/foundation-backend' set up to track remote branch 'rfc/foundation-backend' from 'origin'.
+ git rebase origin/master
First, rewinding head to replay your work on top of it...
Applying: init
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
CONFLICT (add/add): Merge conflict in terraform/services/main.tf
Auto-merging terraform/services/main.tf
CONFLICT (add/add): Merge conflict in terraform/permissions/main.tf
Auto-merging terraform/permissions/main.tf
CONFLICT (add/add): Merge conflict in terraform/infrastructure/main.tf
Auto-merging terraform/infrastructure/main.tf
CONFLICT (add/add): Merge conflict in docker-compose.yml
Auto-merging docker-compose.yml
CONFLICT (add/add): Merge conflict in README.md
Auto-merging README.md
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging .gitignore
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 init
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
##[error]Docker run failed with exit code 1
```

# Manual

```
$ cd /tmp/
dogmatic69@dogmatic69:/tmp$ git clone git@github.com:redacted/data-foundation.git
Cloning into 'data-foundation'...
........
Resolving deltas: 100% (2622/2622), done.
dogmatic69@dogmatic69:/tmp$ cd data-foundation/
✔ /tmp/data-foundation [master|✔] 
22:14 $ git fetch origin rfc/foundation-backend
From github.com:redacted/data-foundation
 * branch            rfc/foundation-backend -> FETCH_HEAD
✔ /tmp/data-foundation [master|✔] 
22:14 $ git checkout -b rfc/foundation-backend origin/rfc/foundation-backend
Branch 'rfc/foundation-backend' set up to track remote branch 'rfc/foundation-backend' from 'origin'.
Switched to a new branch 'rfc/foundation-backend'
✔ /tmp/data-foundation [rfc/foundation-backend|✔] 
22:14 $ git rebase origin/master
First, rewinding head to replay your work on top of it...
Applying: docs: Initial draft of foundation backend
```

# info re the PR branch vs master.
```
$ git status 
On branch rfc/foundation-backend
Your branch and 'origin/rfc/foundation-backend' have diverged,
and have 2 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

# this is just the PR before master was updated
$ git diff master..HEAD --shortstat 
 1 file changed, 225 insertions(+)

# diff between master and PR where master has 1 extra commit to a different file
$ git diff master..HEAD --shortstat 
 2 files changed, 225 insertions(+), 3 deletions(-)

# change on master
$ git show master --shortstat 
.....
 1 file changed, 3 insertions(+)

$ git log --oneline | grep init
37ac58d init

$ git log 37ac58d..master --oneline | wc -l
589
```

That last command shows that it is rebasing 589 commits back because master is one commit ahead?

**Comment by fkorotkov** [comment]
Sorry for a delayed response. Finally got some time to investigate. Seems some changes to `actions/checkout` broke this actions. Please explicitly specify `actions/checkout@v1.2.0`.

**Comment by dogmatic69** [comment]
Nice find, Could you link the change that broke it? I will this version and report back

**Comment by fkorotkov** [comment]
I actually didn't find the exact change. Here is how I found it:

* Checked locally on my Mac and rebase worked.
* Checked in a `alpine:latest` container locally and merge worked.
* Then decided to check how the repository is cloned and remembered that the `checkout` action is used.
* Found out that there was a major release that timed with the issue and tried the previous release which worked.

There is a pretty big v2.0 that just got released. I suspect that the *Fetches only a single commit by default* change broke it which is great if you run builds but to rebase you need a full history.

**Comment by fkorotkov** [comment]
Yeah, you can make it work with the latest `checkout` action by using `fetch-depth` parameter:

```yaml
- uses: actions/checkout@master
    with:
      fetch-depth: 0
```

Updated docs in de548bc6c719045e5d64640659f07e5919f33022

**Comment by ErikSchierboom** [comment]
Ah right! Thanks so much for finding the solution! 🎉
