### ISSUE TITLE
make rebase on comment optional

### ISSUE THREAD

**Issue by carbohydrates** [cirrus-actions/rebase#34]
I want to use this action on pull request automatically
I want to have a way to disable rebase command checks  https://github.com/cirrus-actions/rebase/blob/master/entrypoint.sh#L9-L11
I propose to add the REBASE_ON_COMMENT=true|false variable

**Comment by fkorotkov** [comment]
So you want to always rebase a newly open PR?

**Comment by fkorotkov** [comment]
BTW we can remove this lines since it's a legacy check before actions started supporting `if` like this:

```yaml
if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
```

The lines you are refering are always true in this case.

In you case you'll need to create a separate action config with something like:

```yaml
on: 
  pull_request:
    types: [created]
```

and without such if statement.

**Comment by carbohydrates** [comment]
I want to rebase each commit that made in the PR branch after PR was opened.
So if you remove these checks in https://github.com/cirrus-actions/rebase/blob/master/entrypoint.sh
This will work for me. Because, as you mention above,  with providing  `if` block GitHub Actions achieve more flexibility, so hardcoded checks should be removed.
Thanks in advance.

**Comment by fkorotkov** [comment]
I'm AFK at the moment. Do you want to make a PR to remove those lines? 😅

**Comment by carbohydrates** [comment]
Unfortunately, I cannot push to this repository.
```
(⎈ |N/A:N/A)➜  rebase git:(feature/remove-legacy-checks) git push --set-upstream origin feature/remove-legacy-checks

ERROR: Permission to cirrus-actions/rebase.git denied to carbohydrates.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```


this is my update, I kindly asking you to delete these legacy checks from the `entrypoint.sh`.
thank you
