### ISSUE TITLE
After rebase is done new pull_request/push event doesn't trigger the workflow

### ISSUE THREAD

**Issue by jurenovic** [cirrus-actions/rebase#39]
Hello
I tried to set this thing up but however I've put it it didn't fire the workflow after the pull request was rebased.

I have created a very simple repo demonstrating the  issue. Branch master is protected and it needs to be up to date before merging. In the sample there is a master and a feature branch.
```
* 86bd7db (HEAD -> master, origin/master) third master
| * 4c8948b (origin/feature-1, feature-1) feature first
|/
* 001c1ee second master
* b688c44 first commit
```
the repo is https://github.com/jurenovic/test-rebase

Can you please help me since I would really like having rebasing feature from PR comments.

Many thanks

**Comment by fkorotkov** [comment]
It's Actions limitation. See [docs](https://help.github.com/en/actions/reference/events-that-trigger-workflows):

> An action in a workflow run can't trigger a new workflow run. For example, if an action pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

There is also discussion on developer forum: https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676

**Comment by jurenovic** [comment]
Thank you. I have tried it with a bot access token and it works. As a suggestion maybe add a line about this to the readme.

**Comment by sebastian-toepfer** [comment]
@jurenovic: same issue, but doesn't understand your solution. can you explain me what you mean with a bot access token, please.

**Comment by jurenovic** [comment]
@sebastian-toepfer In our company we have a github user (a bot account) from times of Jenkins. So for this to work properly I have used bot user personal access token.

**Comment by sebastian-toepfer** [comment]
@jurenovic: thanks, okay we use an access-token from a normal user, but it doesn't work.
