### ISSUE TITLE
Rebase does nothing

### ISSUE THREAD

**Issue by Borda** [cirrus-actions/rebase#43]
Hello, I have probably a question why the rebase doesn't do anything? I was using the example from readme but still when I type `/rebase` nothing is happening... 
see the repo PR https://github.com/PyTorchLightning/pytorch-lightning/pull/1680#issuecomment-622458405

**Comment by fkorotkov** [comment]
See https://github.com/PyTorchLightning/pytorch-lightning/pull/1695

**Comment by Borda** [comment]
Thx, let's see how it works...

**Comment by Borda** [comment]
just curious if there some delay or when it will be rebased?
https://github.com/PyTorchLightning/pytorch-lightning/pull/1723#issuecomment-623406181

**Comment by fkorotkov** [comment]
You can check all Actions Runs here: https://github.com/PyTorchLightning/pytorch-lightning/actions?query=workflow%3A%22Automatic+Rebase%22

In your particular case it failed https://github.com/PyTorchLightning/pytorch-lightning/runs/642599204?check_suite_focus=true#step:4:10

See #12 and this comment particularly https://github.com/cirrus-actions/rebase/issues/12#issuecomment-531290309

**Comment by Borda** [comment]
but we already have this env there
https://github.com/PyTorchLightning/pytorch-lightning/blob/d28b1453934b9facbe6d6613f943087d2eac35bd/.github/workflows/rebase.yml#L19-L20
