### ISSUE TITLE
Limit to users with write permissions

### ISSUE THREAD

**Issue by matthijskooijman** [cirrus-actions/rebase#49]
AFAICS this action now allows *anyone* to comment "/rebase" and the PR will be rebased. It would be good if this could be limited to comments written by users with write permissions on the repo or branch (e.g. anyone who could otherwise also push to the the branch). Not sure how you would check this exactly, though (haven't looked at actions docs yet).

**Comment by fkorotkov** [comment]
You can add something like `github.event.comment.author_association == 'MEMBER'` to the `if` statement to allow only organization members to call the action.

See [documentation](https://developer.github.com/v4/enum/commentauthorassociation/) for available values
