### ISSUE TITLE
Error: fatal: A branch named 'master' already exists

### ISSUE THREAD

**Issue by glenn-jocher** [cirrus-actions/rebase#58]
Hi, thanks for this great action! I installed in our repo and ran into an error the first time I tried to use it on this PR https://github.com/ultralytics/yolov5/pull/395

A user is trying to submit a PR from their forked branch master to origin/master: 

> wants to merge 12 commits into ultralytics:master from topiaruss:master

`fatal: A branch named 'master' already exists.`

<img width="1015" alt="Screen Shot 2020-08-01 at 2 04 55 PM" src="https://user-images.githubusercontent.com/26833433/89110501-ff34e800-d3ff-11ea-9faa-1136bd93bcb9.png">

**Comment by Koenkk** [comment]
Same issue here (https://github.com/Koenkk/zigbee2mqtt/runs/984238831?check_suite_focus=true)
