### ISSUE TITLE
Does not trigger

### ISSUE THREAD

**Issue by aminya** [cirrus-actions/rebase#60]
I am trying to make this work, but it does not trigger:
https://github.com/atom-ide-community/atom/pull/125

Here is my configuration:
https://github.com/atom-ide-community/atom/blob/master/.github/rebase.yml

**Comment by fkorotkov** [comment]
Do you have actions enabled for your fork here https://github.com/atom-ide-community/atom/actions?

**Comment by aminya** [comment]
It is enabled by default 🤔 
![image](https://user-images.githubusercontent.com/16418197/93549340-b644de80-f92e-11ea-90f2-8e8b4af5a178.png)

**Comment by fkorotkov** [comment]
Oh, I think you need to put all actions in `.github/workflows` folder and not just `.github`. I don't see any actions triggering for your repository.

**Comment by aminya** [comment]
Oh, sorry! That was my mistake. I just followed my upstream's pattern without considering that this one is an Github action!

**Comment by aminya** [comment]
Thank you the issue is fixed! 👍
