### ISSUE TITLE
Cannot rebase because of Github security issue

### ISSUE THREAD

**Issue by gent-ahmeti** [cirrus-actions/rebase#92]
Looks like this action is affected by: https://github.blog/2022-04-12-git-security-vulnerability-announced/

More information can be found in this thread: https://github.com/actions/checkout/issues/760

Since the rebase is running on a Docker container we can't use the workaround given in this thread, making `/github/workspace` a safe directory

I think the solution is to use the latest `git` version inside the Docker container

Error that I'm getting with version 1.4:
```
Collecting information about PR #*PR number* of *Repo name*...
Base branch for PR #*PR number* is *Base branch*
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

**Comment by dana-ciocan** [comment]
Also experiencing this issue here

**Comment by aliammaar** [comment]
> Looks like this action is affected by: https://github.blog/2022-04-12-git-security-vulnerability-announced/
> 
> More information can be found in this thread: [actions/checkout#760](https://github.com/actions/checkout/issues/760)
> 
> Since the rebase is running on a Docker container we can't use the workaround given in this thread, making `/github/workspace` a safe directory
> 
> I think the solution is to use the latest `git` version inside the Docker container
> 
> Error that I'm getting with version 1.4:
> 
> ```
> Collecting information about PR #*PR number* of *Repo name*...
> Base branch for PR #*PR number* is *Base branch*
> fatal: unsafe repository ('/github/workspace' is owned by someone else)
> To add an exception for this directory, call:
> 
> 	git config --global --add safe.directory /github/workspace
> ```

+1

**Comment by tn3rb** [comment]
getting a very similar error today:

```
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

**Comment by pridumkuvatyj** [comment]
Getting the same error also.
